name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Instalar o Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Definir versão do Python no Poetry
        run: poetry env use python3

      - name: Atualizar poetry.lock
        run: poetry lock --no-interaction  # Corrige a inconsistência no lock file

      - name: Instalar dependências com Poetry
        run: poetry install --no-root --directory .

      - name: Corrigir fim de arquivo (W292)
        run: sed -i -e '$a\' jogo.py  # Garante uma linha em branco no final do arquivo

      - name: Verificar PEP8
        run: poetry run flake8 jogo.py

      - name: Verificar Lint
        run: poetry run pylint jogo.py

